name: Release Build for Docker Plugin

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      manual:
        description: Manual run (bypass default conditions)
        type: boolean
        default: true

jobs:
  build_docker_volume_plugin:
    if: inputs.manual || github.repository == 'rclone/rclone'
    name: Build docker plugin job
    runs-on: ubuntu-latest
    steps:
      - name: Free some space
        shell: bash
        run: |
          df -h .
          # Remove android SDK
          sudo rm -rf /usr/local/lib/android || true
          # Remove .net runtime
          sudo rm -rf /usr/share/dotnet || true
          df -h .
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and publish docker plugin
        shell: bash
        run: |
          VER=${GITHUB_REF#refs/tags/}
          PLUGIN_USER=ghcr.io/${{ github.repository }}
          BASE_IMAGE=ghcr.io/ridesnails/filen-rclone:latest
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username ${{ github.actor }} --password-stdin
          for PLUGIN_ARCH in amd64 arm64 arm/v7 arm/v6 ;do
              export PLUGIN_USER PLUGIN_ARCH BASE_IMAGE
              make docker-plugin PLUGIN_TAG=${PLUGIN_ARCH/\//-} BASE_IMAGE=${BASE_IMAGE}
              make docker-plugin PLUGIN_TAG=${PLUGIN_ARCH/\//-}-${VER#v} BASE_IMAGE=${BASE_IMAGE}
          done
          make docker-plugin PLUGIN_ARCH=amd64 PLUGIN_TAG=latest BASE_IMAGE=${BASE_IMAGE}
          make docker-plugin PLUGIN_ARCH=amd64 PLUGIN_TAG=${VER#v} BASE_IMAGE=${BASE_IMAGE}
