---
# Github Actions release for rclone
# -*- compile-command: "yamllint -f parsable build_publish_docker_plugin.yml" -*-

name: Release Build for Docker Plugin

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      manual:
        description: Manual run (bypass default conditions)
        type: boolean
        default: true
jobs:
  build_docker_volume_plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Free some space
        run: |
          sudo apt-get clean
          docker image prune -a -f || true

      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish docker plugin
        run: |
          VER=${GITHUB_REF#refs/tags/}
          docker buildx inspect | grep -q /amd64 || \
            docker run --rm --privileged tonistiigi/binfmt --install all
          rm -rf ./build/docker-plugin
          docker buildx build \
            --no-cache --pull \
            --build-arg BASE_IMAGE=ghcr.io/ridesnails/filen-rclone:master \
            --platform linux/amd64 \
            --output ./build/docker-plugin/rootfs \
            ./contrib/docker-plugin/managed
